export const VARIABLE_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION: 'JWT_EXPIRATION',
  DATABASE_NAME: 'DATABASE_NAME',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_USER: 'DATABASE_USER',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
} as const;

export type VariableKey = (typeof VARIABLE_KEYS)[keyof typeof VARIABLE_KEYS];
