export const VAR_ENV_KEYS = {
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION: 'JWT_EXPIRATION',
  JWT_REFRESH_EXPIRATION: 'JWT_REFRESH_EXPIRATION',
  DATABASE_NAME: 'DATABASE_NAME',
  DATABASE_PORT: 'DATABASE_PORT',
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_USER: 'DATABASE_USER',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  ADMIN_PASSWORD: 'ADMIN_PASSWORD',
  ADMIN_EMAIL: 'ADMIN_EMAIL',
} as const;

export type VariableKey = (typeof VAR_ENV_KEYS)[keyof typeof VAR_ENV_KEYS];
